[build]
builder = "nixpacks"
buildCommand = "npm run build:railway"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
FRONTEND_URL = "https://your-frontend-domain.vercel.app"
